export const SITUATION_EVENTS = [
  {
    id: 'S01',
    type: 'situation',
    name: '전쟁 발발',
    desc: '인근 지역에서 무력 충돌이 시작됐습니다. 물류비가 급등합니다.',
    minFloor: 10,
    phaseWeight: { boom: 0.5, growth: 0.7, stable: 1.0, contraction: 1.5, recession: 2.0 },
    autoEffect: { costMul: 1.2, duration: 3 },
    educationHint: '전쟁은 공급망을 교란해 원가를 상승시킵니다.',
  },
  {
    id: 'S02',
    type: 'situation',
    name: '유전 발견',
    desc: '대규모 유전이 발견되어 원자재 가격이 하락했습니다.',
    minFloor: 5,
    phaseWeight: { boom: 1.5, growth: 1.2, stable: 1.0, contraction: 0.8, recession: 0.5 },
    autoEffect: { costMul: 0.85, duration: 4 },
    educationHint: '공급 증가는 가격 하락을 유발합니다.',
  },
  {
    id: 'S03',
    type: 'situation',
    name: '금리 인상',
    desc: '중앙은행이 기준금리를 인상했습니다.',
    minFloor: 1,
    phaseWeight: { boom: 2.0, growth: 1.5, stable: 1.0, contraction: 0.5, recession: 0.3 },
    autoEffect: { interestRateAdd: 0.02, duration: 5 },
    educationHint: '금리 인상은 투자 비용을 높이고 소비를 위축시킵니다.',
  },
  {
    id: 'S04',
    type: 'situation',
    name: '금리 인하',
    desc: '경기 부양을 위해 금리를 인하했습니다.',
    minFloor: 1,
    phaseWeight: { boom: 0.3, growth: 0.5, stable: 1.0, contraction: 1.5, recession: 2.0 },
    autoEffect: { interestRateAdd: -0.015, duration: 5 },
    educationHint: '금리 인하는 소비와 투자를 촉진합니다.',
  },
  {
    id: 'S05',
    type: 'situation',
    name: '자연재해',
    desc: '대형 태풍이 물류 항만을 강타했습니다.',
    minFloor: 15,
    phaseWeight: { boom: 1.0, growth: 1.0, stable: 1.0, contraction: 1.0, recession: 1.0 },
    autoEffect: { demandMul: 0.85, costMul: 1.15, duration: 2 },
    educationHint: '외부 충격은 수요와 공급을 동시에 교란할 수 있습니다.',
  },
  {
    id: 'S06',
    type: 'situation',
    name: '기술 혁신 발표',
    desc: '글로벌 기업이 획기적인 신기술을 발표했습니다. 시장 기대감 상승.',
    minFloor: 20,
    phaseWeight: { boom: 2.0, growth: 1.8, stable: 1.0, contraction: 0.5, recession: 0.3 },
    autoEffect: { demandMul: 1.15, duration: 3 },
    educationHint: '기술 혁신은 새로운 수요를 창출합니다.',
  },
  {
    id: 'S07',
    type: 'situation',
    name: '정부 소비 진작 정책',
    desc: '정부가 소비 쿠폰을 배포하며 내수 진작에 나섰습니다.',
    minFloor: 10,
    phaseWeight: { boom: 0.5, growth: 0.8, stable: 1.0, contraction: 1.8, recession: 2.5 },
    autoEffect: { demandMul: 1.2, duration: 3 },
    educationHint: '정부의 재정정책은 총수요를 증가시킵니다.',
  },
  {
    id: 'S08',
    type: 'situation',
    name: '환율 급변동',
    desc: '원달러 환율이 급격히 상승했습니다.',
    minFloor: 10,
    phaseWeight: { boom: 0.8, growth: 1.0, stable: 1.2, contraction: 1.5, recession: 1.8 },
    autoEffect: { costMul: 1.1, duration: 4 },
    educationHint: '환율 상승은 수입 원자재 가격을 높입니다.',
  },
  {
    id: 'S09',
    type: 'situation',
    name: '인플레이션 급등',
    desc: '물가가 빠르게 오르고 있습니다. 소비자 구매력이 감소합니다.',
    minFloor: 20,
    phaseWeight: { boom: 1.5, growth: 1.2, stable: 0.8, contraction: 0.5, recession: 0.3 },
    autoEffect: { demandMul: 0.9, costMul: 1.1, duration: 4 },
    educationHint: '인플레이션은 실질 구매력을 떨어뜨립니다.',
  },
  {
    id: 'S10',
    type: 'situation',
    name: '전염병 확산',
    desc: '신종 전염병이 확산되며 소비 패턴이 급변했습니다.',
    minFloor: 30,
    phaseWeight: { boom: 0.3, growth: 0.5, stable: 1.0, contraction: 1.5, recession: 2.0 },
    autoEffect: { demandMul: 0.75, duration: 5 },
    educationHint: '외부 충격은 예측 불가능한 수요 변화를 일으킵니다.',
  },
]

export const PLAYER_EVENTS = [
  {
    id: 'P01',
    type: 'player',
    name: '공장 화재',
    desc: '공장에 화재가 발생했습니다.',
    requireFactory: true,
    minFloor: 1,
    phaseWeight: { boom: 1.0, growth: 1.0, stable: 1.0, contraction: 1.2, recession: 1.5 },
    choices: [
      {
        id: 'c1',
        label: '즉시 복구 (2천만)',
        type: 'safe',
        outcomes: [{ p: 1.0, effect: 'capital', v: -20_000_000, msg: '복구 완료' }],
      },
      {
        id: 'c2',
        label: '보험 청구',
        type: 'normal',
        outcomes: [
          { p: 0.7, effect: 'capital', v: -5_000_000, msg: '보험 처리 완료 -500만' },
          { p: 0.3, effect: 'shutdown', v: 2, msg: '보험 거절! 2턴 정지' },
        ],
      },
      {
        id: 'c3',
        label: '그냥 둔다',
        type: 'gamble',
        outcomes: [
          { p: 0.4, effect: 'none', v: 0, msg: '자연 진화됐습니다' },
          { p: 0.6, effect: 'shutdown', v: 3, msg: '전소! 3턴 정지' },
        ],
      },
    ],
  },
  {
    id: 'P02',
    type: 'player',
    name: '세무조사 예고',
    desc: '국세청으로부터 세무조사 예고장이 도착했습니다.',
    requireDebt: false,
    minFloor: 15,
    boostOnHighCap: true,
    phaseWeight: { boom: 1.5, growth: 1.2, stable: 1.0, contraction: 0.8, recession: 0.5 },
    choices: [
      {
        id: 'c1',
        label: '로펌 고용 (5천만)',
        type: 'safe',
        outcomes: [{ p: 1.0, effect: 'capital', v: -50_000_000, msg: '무사 통과' }],
      },
      {
        id: 'c2',
        label: '정면 돌파',
        type: 'gamble',
        outcomes: [
          { p: 0.5, effect: 'brand', v: 10, msg: '모범납세자! 브랜드 +10' },
          { p: 0.5, effect: 'capital', v: -999, msg: '탈세 적발! 현금 반토막' },
        ],
      },
    ],
  },
  {
    id: 'P03',
    type: 'player',
    name: '인플루언서 협찬 요청',
    desc: '구독자 500만 인플루언서가 협찬을 요청했습니다.',
    requireBrand: true,
    minFloor: 5,
    phaseWeight: { boom: 2.0, growth: 1.5, stable: 1.0, contraction: 0.8, recession: 0.5 },
    choices: [
      {
        id: 'c1',
        label: '수락 (1천만)',
        type: 'normal',
        outcomes: [
          { p: 0.6, effect: 'demandMul', v: 0.3, msg: '바이럴 성공! 수요 +30%' },
          { p: 0.4, effect: 'brand', v: -15, msg: '뒷광고 논란 브랜드 -15' },
        ],
      },
      {
        id: 'c2',
        label: '거절',
        type: 'safe',
        outcomes: [{ p: 1.0, effect: 'none', v: 0, msg: '정중히 거절했습니다' }],
      },
      {
        id: 'c3',
        label: '역제안 (500만)',
        type: 'normal',
        outcomes: [
          { p: 0.5, effect: 'demandMul', v: 0.15, msg: '절충안 성공! 수요 +15%' },
          { p: 0.5, effect: 'none', v: 0, msg: '협상 결렬' },
        ],
      },
    ],
  },
  {
    id: 'P04',
    type: 'player',
    name: '창고의 정체불명 버섯',
    desc: '창고에서 정체불명의 버섯이 발견됐습니다.',
    requireFactory: true,
    minFloor: 1,
    phaseWeight: { boom: 1.0, growth: 1.0, stable: 1.0, contraction: 1.0, recession: 1.0 },
    choices: [
      {
        id: 'c1',
        label: '즉시 폐기',
        type: 'safe',
        outcomes: [{ p: 1.0, effect: 'capital', v: -1_000_000, msg: '폐기 처리 -100만' }],
      },
      {
        id: 'c2',
        label: '신약 개발 투자',
        type: 'absurd',
        outcomes: [
          { p: 0.1, effect: 'capital', v: 1_000_000_000, msg: '기적의 영약! +10억' },
          { p: 0.9, effect: 'capital', v: -50_000_000, msg: '단순 곰팡이 -5천만' },
        ],
      },
      {
        id: 'c3',
        label: '직원들이 먹어본다',
        type: 'absurd',
        outcomes: [
          { p: 0.3, effect: 'resist', v: 0.05, msg: '사기 충천! 저항성 +5%' },
          { p: 0.4, effect: 'none', v: 0, msg: '아무 일도 없었습니다' },
          { p: 0.3, effect: 'shutdown', v: 1, msg: '집단 식중독! 1턴 정지' },
        ],
      },
    ],
  },
  {
    id: 'P05',
    type: 'player',
    name: '핵심 직원 이직 제안',
    desc: '경쟁사가 핵심 임원에게 연봉 2배를 제안했습니다.',
    requireFactory: false,
    minFloor: 10,
    phaseWeight: { boom: 1.5, growth: 1.2, stable: 1.0, contraction: 0.8, recession: 0.5 },
    choices: [
      {
        id: 'c1',
        label: '연봉 인상 대응 (월 1천)',
        type: 'normal',
        outcomes: [
          { p: 0.8, effect: 'capital', v: -10_000_000, msg: '인재 유지 -1천만' },
          { p: 0.2, effect: 'costMul', v: 0.08, msg: '그래도 이직' },
        ],
      },
      {
        id: 'c2',
        label: '보내준다',
        type: 'safe',
        outcomes: [
          { p: 0.6, effect: 'none', v: 0, msg: '후임자 발굴 예정' },
          { p: 0.4, effect: 'costMul', v: 0.08, msg: '업무 공백 운영비 +8%' },
        ],
      },
    ],
  },
  {
    id: 'P06',
    type: 'player',
    name: '은행 특별 저금리 프로모션',
    desc: '거래 은행이 한시적 저금리 대출을 제안했습니다.',
    requireDebt: false,
    minFloor: 5,
    phaseWeight: { boom: 0.5, growth: 0.8, stable: 1.0, contraction: 1.5, recession: 2.0 },
    choices: [
      {
        id: 'c1',
        label: '3억 대출',
        type: 'normal',
        outcomes: [
          { p: 0.85, effect: 'capital', v: 300_000_000, msg: '3억 우대금리 대출 완료' },
          { p: 0.15, effect: 'none', v: 0, msg: '한도 초과 거절' },
        ],
      },
      {
        id: 'c2',
        label: '패스',
        type: 'safe',
        outcomes: [{ p: 1.0, effect: 'none', v: 0, msg: '현재 재무 상황 유지' }],
      },
    ],
  },
  {
    id: 'P07',
    type: 'player',
    name: '경쟁사 특허 만료',
    desc: '라이벌의 핵심 특허가 이번 달 만료됩니다.',
    requireFactory: false,
    minFloor: 20,
    boostOnRivals: true,
    phaseWeight: { boom: 1.5, growth: 1.3, stable: 1.0, contraction: 0.8, recession: 0.6 },
    choices: [
      {
        id: 'c1',
        label: '기술 즉시 도입 (5천)',
        type: 'normal',
        outcomes: [
          { p: 0.8, effect: 'quality', v: 20, msg: '품질 점수 +20!' },
          { p: 0.2, effect: 'none', v: 0, msg: '기술 도입 예상보다 어려움' },
        ],
      },
      {
        id: 'c2',
        label: '관망',
        type: 'safe',
        outcomes: [{ p: 1.0, effect: 'none', v: 0, msg: '경쟁사도 대응했습니다' }],
      },
    ],
  },
  {
    id: 'P08',
    type: 'player',
    name: '해킹 랜섬웨어',
    desc: '회사 시스템이 랜섬웨어에 감염됐습니다.',
    requireFactory: false,
    minFloor: 20,
    boostOnHighCap: true,
    phaseWeight: { boom: 1.0, growth: 1.0, stable: 1.2, contraction: 1.3, recession: 1.5 },
    choices: [
      {
        id: 'c1',
        label: '몸값 지불 (5천)',
        type: 'normal',
        outcomes: [
          { p: 0.7, effect: 'capital', v: -50_000_000, msg: '시스템 복구 -5천만' },
          { p: 0.3, effect: 'shutdown', v: 1, msg: '먹튀! 추가 1턴 정지' },
        ],
      },
      {
        id: 'c2',
        label: '자체 복구',
        type: 'gamble',
        outcomes: [
          { p: 0.5, effect: 'shutdown', v: 1, msg: '1턴 정지 후 복구' },
          { p: 0.5, effect: 'shutdown', v: 2, msg: '복구 실패 2턴 정지' },
        ],
      },
    ],
  },
  {
    id: 'P09',
    type: 'player',
    name: '소비자 단체 우수기업 선정',
    desc: '소비자 단체가 자사를 이달의 우수기업으로 선정했습니다.',
    requireBrand: true,
    minFloor: 15,
    phaseWeight: { boom: 1.5, growth: 1.3, stable: 1.0, contraction: 0.7, recession: 0.5 },
    choices: [
      {
        id: 'c1',
        label: '적극 홍보 (1천)',
        type: 'normal',
        outcomes: [
          { p: 0.85, effect: 'brand', v: 20, msg: '브랜드 +20!' },
          { p: 0.15, effect: 'none', v: 0, msg: '홍보 효과 미미' },
        ],
      },
      {
        id: 'c2',
        label: '조용히 수상',
        type: 'safe',
        outcomes: [{ p: 1.0, effect: 'brand', v: 8, msg: '조용한 브랜드 +8' }],
      },
    ],
  },
  {
    id: 'P10',
    type: 'player',
    name: '길가의 쓰레기',
    desc: '출근길에 쓰레기를 발견했습니다.',
    requireFactory: false,
    minFloor: 1,
    phaseWeight: { boom: 1.0, growth: 1.0, stable: 1.0, contraction: 1.0, recession: 1.0 },
    choices: [
      {
        id: 'c1',
        label: '줍는다',
        type: 'normal',
        outcomes: [
          { p: 0.8, effect: 'brand', v: 10, msg: '친환경 이미지 브랜드 +10' },
          { p: 0.2, effect: 'brand', v: -15, msg: '무단투기 오해 브랜드 -15' },
        ],
      },
      {
        id: 'c2',
        label: '무시한다',
        type: 'safe',
        outcomes: [{ p: 1.0, effect: 'none', v: 0, msg: '별일 없었습니다' }],
      },
      {
        id: 'c3',
        label: '내 것도 버린다',
        type: 'absurd',
        outcomes: [
          { p: 0.2, effect: 'resist', v: 0.05, msg: '현대미술 인정! 저항성 +5%' },
          { p: 0.4, effect: 'none', v: 0, msg: '아무도 안 봤습니다' },
          { p: 0.4, effect: 'capital', v: -5_000_000, msg: '무단투기 벌금 -500만' },
        ],
      },
    ],
  },
]

export {
  EVENT_CARDS as DOC_EVENTS,
  drawWeightedEventCards,
  getEventCardById,
} from './eventCards.js'
