export const RIVAL_ORDER = ['megaflex', 'aura', 'memecatch', 'nexuscore']

export const RIVALS = {
  megaflex: {
    id: 'megaflex',
    name: '메가플렉스',
    icon: '🏭',
    archetype: '덤핑 공세형',
    color: '#FF8A65',
    pattern: 'aggressive',
    joinFloor: 1,
    initialCapital: 30000000,
    bossFloor: 20,
    bossCondition: '5턴 연속 점유율 25% 이상 유지',
    bossThreshold: { metric: 'marketShare', value: 0.25, consecutiveTurns: 5 },
    basePrice: 69000,
    startingShare: 0.23,
    brandPower: 84,
    qualityPower: 82,
    aggression: 1.35,
    volatility: 0.9,
    cadenceOffset: 0,
    undercutCap: 4.4,
    summary: '가격을 먼저 흔들어 시장을 잠식하는 대형 경쟁사',
    weakPhase: ['boom', 'growth'],
    strongPhase: ['contraction', 'recession'],
  },
  aura: {
    id: 'aura',
    name: '아우라',
    icon: '💎',
    archetype: '프리미엄 브랜드형',
    color: '#F6C453',
    pattern: 'premium',
    joinFloor: 10,
    initialCapital: 40000000,
    bossFloor: 40,
    bossCondition: '브랜드 가치 150pt 이상 달성',
    bossThreshold: { metric: 'brandValue', value: 150 },
    basePrice: 108000,
    startingShare: 0.18,
    brandPower: 128,
    qualityPower: 106,
    aggression: 0.88,
    volatility: 0.45,
    cadenceOffset: 1,
    undercutCap: 2.1,
    summary: '가격보다 이미지와 체급으로 압박하는 프리미엄 경쟁사',
    weakPhase: ['contraction', 'recession'],
    strongPhase: ['boom', 'growth'],
  },
  memecatch: {
    id: 'memecatch',
    name: '밈캐치',
    icon: '📱',
    archetype: '바이럴 변동형',
    color: '#7FE6C5',
    pattern: 'volatile',
    joinFloor: 30,
    initialCapital: 20000000,
    bossFloor: 60,
    bossCondition: '3턴 연속 마케팅 3천만 이상 집행',
    bossThreshold: { metric: 'marketingSpent', value: 30000000, consecutiveTurns: 3 },
    basePrice: 84000,
    startingShare: 0.16,
    brandPower: 96,
    qualityPower: 88,
    aggression: 1.08,
    volatility: 0.8,
    cadenceOffset: 2,
    undercutCap: 3.2,
    summary: '밈과 이슈에 기대 급등락하는 변동형 경쟁사',
    weakPhase: ['stable', 'contraction'],
    strongPhase: ['boom'],
  },
  nexuscore: {
    id: 'nexuscore',
    name: '넥서스코어',
    icon: '🔬',
    archetype: '기술 독점형',
    color: '#8AB4FF',
    pattern: 'techmonopoly',
    joinFloor: null,
    joinCondition: 'industryTier >= 3',
    initialCapital: 80000000,
    bossFloor: 80,
    bossCondition: 'Tier 3 + 품질 점수 200 이상',
    bossThreshold: { metric: 'qualityScore', value: 200, requireTier: 3 },
    basePrice: 132000,
    startingShare: 0.21,
    brandPower: 112,
    qualityPower: 132,
    aggression: 0.76,
    volatility: 0.35,
    cadenceOffset: 3,
    undercutCap: 1.8,
    summary: '기술과 특허로 고급 수요를 잠그는 독점형 경쟁사',
    weakPhase: [],
    strongPhase: ['boom', 'growth', 'stable'],
  },
}

export const RIVAL_NAMES = {
  megaflex: ['메가플렉스', '하이퍼마트', '코어플렉스', '넥스트플렉스', '울트라마트'],
  aura: ['아우라', '루미나', '에클라', '오라클럭스', '셀레스티아'],
  memecatch: ['밈캐치', '버즈웨이브', '바이럴픽', '트렌디코', '픽셀버스트'],
  nexuscore: ['넥서스코어', '퀀텀베이스', '시냅스텍', '코어매트릭스', '제네시스랩'],
}

export const MID_BOSS_EVENTS = {
  10: {
    rivalId: 'megaflex',
    type: 'mid-boss',
    action: '메가플렉스가 이번 달 판매가를 원가 수준까지 내렸습니다.',
    threat: '이번 층 당신의 점유율 -10%',
    effect: { shareDebuff: -0.1 },
  },
  20: {
    rivalId: 'megaflex',
    type: 'boss',
    action: '메가플렉스가 대규모 덤핑 캠페인을 시작했습니다.',
    threat: '10턴간 수요 -20%, 5턴 연속 점유율 25% 이상 유지',
    bossCondition: { metric: 'marketShare', value: 0.25, consecutiveTurns: 5 },
    effect: { demandMul: -0.2 },
  },
  30: {
    rivalId: 'aura',
    type: 'mid-boss',
    action: '아우라가 프리미엄 신제품을 출시했습니다.',
    threat: '브랜드 가치가 낮으면 이번 층 점유율 -8%',
    effect: { brandThreshold: 50, shareDebuff: -0.08 },
  },
  40: {
    rivalId: 'aura',
    type: 'boss',
    action: '아우라가 브랜드 독점을 선언했습니다.',
    threat: '브랜드 가치 150pt 이상 달성',
    bossCondition: { metric: 'brandValue', value: 150 },
  },
  50: {
    rivalId: 'memecatch',
    type: 'mid-boss',
    action: '밈캐치가 바이럴 캠페인을 터뜨렸습니다.',
    threat: '이번 층 수요 변동성 +50%',
    effect: { demandVariance: 0.5 },
  },
  60: {
    rivalId: 'memecatch',
    type: 'boss',
    action: '밈캐치가 전면적 SNS 공세를 시작했습니다.',
    threat: '3턴 연속 마케팅 3천만 이상 집행',
    bossCondition: { metric: 'marketingSpent', value: 30000000, consecutiveTurns: 3 },
  },
  70: {
    rivalId: 'megaflex',
    type: 'mid-boss',
    action: '메가플렉스가 물류망을 장악했습니다.',
    threat: '이번 층 원가 +10%',
    effect: { costDebuff: 0.1 },
  },
  80: {
    rivalId: 'nexuscore',
    type: 'boss',
    action: '넥서스코어가 기술 독점을 완성했습니다.',
    threat: 'Tier 3 + 품질 점수 200 이상 달성',
    bossCondition: { metric: 'qualityScore', value: 200, requireTier: 3 },
    note: 'Tier 3에 도달하지 못했다면 이번 보스는 스킵됩니다.',
  },
  90: {
    rivalId: 'aura',
    type: 'mid-boss',
    action: '아우라가 마지막 프리미엄 공세를 시작했습니다.',
    threat: '이번 층 프리미엄 전략 효과 -30%',
    effect: { premiumDebuff: 0.3 },
  },
  100: {
    rivalId: 'megaflex',
    type: 'boss',
    action: '메가플렉스 최후의 공세. 시장 장악을 선언했습니다.',
    threat: '10턴간 점유율 -15% 페널티, 순자산 3억 유지',
    bossCondition: { metric: 'netWorth', value: 300000000 },
    effect: { shareDebuff: -0.15 },
  },
}

export function createInitialRivals() {
  return RIVAL_ORDER.reduce((rivalState, rivalId) => {
    const rival = RIVALS[rivalId]
    const active = rival.joinFloor === 1

    rivalState[rivalId] = {
      id: rival.id,
      name: RIVAL_NAMES[rivalId][0],
      nameIndex: 0,
      capital: rival.initialCapital,
      initialCapital: rival.initialCapital,
      currentPrice: rival.basePrice,
      marketShare: active ? rival.startingShare * 100 : 0,
      status: active ? '관망중' : '대기중',
      active,
      eliminated: false,
      bankrupt: false,
      bossProgress: 0,
      isAggressive: rival.pattern === 'aggressive',
    }

    return rivalState
  }, {})
}

export function getRivalDefinition(rivalId) {
  return RIVALS[rivalId] ?? RIVALS.megaflex
}
